### ISSUE TITLE
Allows Users from Unauthorized Domain to login in. 

### ISSUE THREAD

**Issue by sdholbrook** [8thwall/google-auth-yourls#2]
After login in using an incorrect google account, and getting the message "
If you hit refresh on the browser you can still access yourls this is obviously very insecure.
![screenshot 2017-08-17 at 00 18 09](https://user-images.githubusercontent.com/8917243/29395903-4db30966-82e2-11e7-8f2f-b9886f53c228.png)

Just hit refresh on the browser and then...

![screenshot 2017-08-17 at 00 18 20](https://user-images.githubusercontent.com/8917243/29395906-53b4fbb2-82e2-11e7-8249-6c6a81ee160d.png)

**Comment by atomarch** [comment]
@sdholbrook Thank you for reporting this.  Should be fixed now.
